### PR TITLE
Fixes #917: Allow Robo to be used with Symfony 5.

### LINKED ISSUE #917: Symfony 5 compatibility
### Steps to reproduce
Add a Symfony 5 package to your `composer.json` file:

```json
{
  "require": {
    "symfony/process": "^5.0.0"
  }
}
```

### Expected behavior
The installation of the Symfony 5 package succeeds.

### Actual behavior

```shell
$ composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - consolidation/robo 2.0.0 requires symfony/process ^4 -> satisfiable by symfony/process[4.0.x-dev, 4.1.x-dev, 4.2.x-dev, 4.3.x-dev, 4.4.x-dev, v4.0.0, v4.0.0-BETA1, v4.0.0-BETA2, v4.0.0-BETA3, v4.0.0-BETA4, v4.0.0-RC1, v4.0.0-RC2, v4.0.1, v4.0.10, v4.0.11, v4.0.12, v4.0.13, v4.0.14, v4.0.15, v4.0.2, v4.0.3, v4.0.4, v4.0.5, v4.0.6, v4.0.7, v4.0.8, v4.0.9, v4.1.0, v4.1.0-BETA1, v4.1.0-BETA2, v4.1.0-BETA3, v4.1.1, v4.1.10, v4.1.11, v4.1.12, v4.1.2, v4.1.3, v4.1.4, v4.1.5, v4.1.6, v4.1.7, v4.1.8, v4.1.9, v4.2.0, v4.2.0-BETA1, v4.2.0-BETA2, v4.2.0-RC1, v4.2.1, v4.2.10, v4.2.11, v4.2.12, v4.2.2, v4.2.3, v4.2.4, v4.2.5, v4.2.6, v4.2.7, v4.2.8, v4.2.9, v4.3.0, v4.3.0-BETA1, v4.3.0-BETA2, v4.3.0-RC1, v4.3.1, v4.3.2, v4.3.3, v4.3.4, v4.3.5, v4.3.6, v4.3.7, v4.3.8, v4.4.0, v4.4.0-BETA1, v4.4.0-BETA2, v4.4.0-RC1] but these conflict with your requirements or minimum-stability.
    - Installation request for consolidation/robo ^2.0.0 -> satisfiable by consolidation/robo[2.0.0].
```

It would be cool if the version constraint of Symfony packages was relaxed. Something like:

```json
{
  "require": {
    "symfony/console": "^4.3.5 || ^5",
    "symfony/event-dispatcher": "^4 || ^5",
    "symfony/filesystem": "^4 || ^5",
    "symfony/finder": "^4 || ^5",
    "symfony/process": "^4 || ^5"
  }
}
```

See the Symfony policy about backward compatibility:
https://symfony.com/doc/current/contributing/community/releases.html#backward-compatibility

### PR DESCRIPTION
**Pull request by greg-1-anderson**
### Overview
This pull request:

- [ ] Fixes a bug
- [x] Adds a feature
- [ ] Breaks backwards compatibility
- [x] Has tests that cover changes
- [ ] Adds or fixes documentation

### Summary
Allow Symfony 5.

### CODE REVIEW

**Comment by greg-1-anderson** [comment]
There's a test failure here from `EventDispatcher::dispatch()` that needs an API update.

We also have a problem with Symfony/Process requiring a factory method instead of a constructor to use a string parameter to exec. We might need to test which version of Symfony/Process we have, as the new factory method is not available in older versions of Symfony/Process (and we'd need to do a major version bump to drop old Symfony/Process versions).

**Comment by alsar** [comment]
The event dispatcher in v5 changed the parameter signature from `string` to `object`. So there needs to be a check (via reflection) which type the function accepts.

For the Process component a simple `method_exists` check should suffice

**Comment by alsar** [comment]
The method `fromShellCommandline` is already available since version 4.2 so there should be no problem to change `new Process($this->getCommand(), getcwd())` to `Process::fromShellCommandline($this->getCommand(), getcwd())` because Robo requires `symfony/process` `^4.4.3|^5`.

**Comment by greg-1-anderson** [comment]
I forgot that I already dropped support for older versions of Symfony/Process in Robo 2. That turns out to have been foresightful; makes things easier here.

**Comment by c33s** [comment]
i won't drop support for a symfony version which is still supported. https://symfony.com/releases/3.4  End of bug fixes: November 2020 End of security fixes: November 2021 

a task runner should be compatible with legacy php and symfony versions as long as possible. bc layers would be awesome.

just my opinion

**Comment by greg-1-anderson** [comment]
Yeah, with more maintainers maybe it wouldn't be a big deal to include more Symfony versions. There's still the Robo 1.x branch for Symfony 3. If you need Symfony 3 AND Symfony 5, you could consider back-porting this PR to the 1.x branch.

Pretty soon we have to think about Composer 2 as well, though; limiting supported versions greatly reduces the testing permutations.

**Comment by greg-1-anderson** [comment]
For those who wish to support a wide variety of Symfony versions, `"consolidation/robo": "^1 | ^2"` should work well in many instances. The Robo 1.x and 2.x APIs are pretty similar.

**Comment by greg-1-anderson** [comment]
This fixed many incompatibilities between Robo and Symfony 5, but not all.

**Pull request merged**
