### PR TITLE
Ensure that environment variables are preserved in Exec #768

### PR DESCRIPTION
**Pull request by q0rban**
### Overview
This pull request:

- [X] Fixes a bug
- [X] Has tests that cover changes

### Summary
See #768

### CODE REVIEW

**Comment by q0rban** [comment]
Getting a false positive on this test: https://travis-ci.org/consolidation/Robo/jobs/421167983#L866

Any ideas on a better way to test this? The test fails on my local, but not on Travis.

**Comment by q0rban** [comment]
Ah, looks like appveyor fails, though: https://ci.appveyor.com/project/greg-1-anderson/robo/build/1.0.568#L845

Good! Now to push up the fixes.

**Comment by greg-1-anderson** [comment]
The behavior of inherited environment variables varies depending on the configuration of your php installation. I don't know if you can downgrade this via an `ini_set`.

**Comment by q0rban** [comment]
@greg-1-anderson I changed the test to count the number of environment variables in 6bd0a72, which I think should make that test more consistent across environments. I tested it on my local without the fix and it failed as expected.

**Comment by q0rban** [comment]
Any thoughts on this @greg-1-anderson ?

**Comment by greg-1-anderson** [comment]
This is okay with passing tests. It looks like only the "lowest" tests are failing. It's okay to just bump the minimum required version of all of the components in the composer.json to be the current version that you have in composer.lock, as long as you do not remove support for any major version of any component (e.g. Symfony 2).

**Comment by greg-1-anderson** [comment]
Maybe it would be better to check in code whether `inheritEnvironmentVariables` is available, and not use it if it is not. That would avoid breaking Symfony 2 builds. I don't think we're ready to require symfony/proces:^3 everywhere here yet.

**Comment by greg-1-anderson** [comment]
That last commit looks like the right approach. Could you back out any unnecessary version pins in composer.json? There's no need to get this exactly right, but it'd be better to keep unrelated components at the same minimum version on a best-effort basis.

**Comment by q0rban** [comment]
It probably wasn't obvious from the commit when you looked at it, but I had reverted back to prior to the version changes to composer.json, made changes to check for the existence of the function (after realizing that no version of Symfony 2.x's Process had the function), and force pushed so that none of those version changes would be in the PR.

**Comment by greg-1-anderson** [comment]
Looks great -- thanks for pushing this through to completion.

**Pull request merged**
