### PR TITLE
[FEATURE] Replace lurker package

### PR DESCRIPTION
**Pull request by pixelbrackets**
### Overview

This pull request:

- [x] Fixes a bug
- [ ] Adds a feature
- [ ] Breaks backwards compatibility
- [ ] Has tests that cover changes
- [ ] Adds or fixes documentation

### Summary

Backport of #1007 to branch 2.x

### CODE REVIEW

**Comment by greg-1-anderson** [comment]
Merged via #1007

**Comment by pixelbrackets** [comment]
@greg-1-anderson Thanks for merging #1007 into 3.x so quickly. :+1: Please note that this PR here (1008) is a backport of the same commit into the *2.x* branch. Could you please re-open and merge it into 2.x? (or you cherry-pick commit 8e5d1f749104abe6194d335f8f4a4707bb0089c6 into 2.x)

**Comment by pixelbrackets** [comment]
Thank you for the quick release of a new version :) :100: :100:

**Comment by greg-1-anderson** [comment]
Ah you're right this one is different.

**Pull request merged**
