### PR TITLE
README cleanup

### PR DESCRIPTION
**Pull request by OGProgrammer**
### Overview

This pull request cleans up the README
### Summary

Changed composer command so it works without having to mess with your minimum stability settings. When 1.0 is released, this can be changed back to ~1. Fixed clean task syntax errors. Removed php close tags.
### Description

See summary.

### CODE REVIEW

**Comment by greg-1-anderson** [comment]
Overall LGTM, except I know that @DavertMik is going to tag 1.0.0 stable soon, so I don't want to merge this and have the install instructions accidentally get included in the stable tag. Otherwise okay to merge, as far as I am concerned.

**Comment by OGProgrammer** [comment]
Pushed ~1 back to the readme, hope to see v1 soon! I know co-workers giving me crap for using "beta" software. Robo rocks!

**Comment by greg-1-anderson** [comment]
Thanks for this.

Robo 1.0.0-RC3 is essentially the 1.0.0 stable release; it just needs to be tagged. There will be a short delay, as @DavertMik is traveling.

**Comment by greg-1-anderson** [comment]
Now I am going to actually merge this, as I intended to do 5 days ago.

**Pull request merged**
