### PR TITLE
Issue #1102 - Makes \Robo\Config\Config compatible with \Dflydev\DotAccessData\Data

### PR DESCRIPTION
**Pull request by Sweetchuck**
Issue #1102

### Overview
This pull request:

- [x] Fixes a bug
- [ ] Adds a feature
- [ ] Breaks backwards compatibility
- [ ] Has tests that cover changes
- [ ] Adds or fixes documentation

### CODE REVIEW

**Comment by greg-1-anderson** [comment]
We don't want to change the function signature of the constructor until the next major version, to preserve backwards compatibility. Could you fix up the value in the body, as done in  https://github.com/consolidation/config/commit/fde7dfee1885ecca9afa3adb8442711d92a5c8ce?

**Comment by Sweetchuck** [comment]
My first try was to change this in \Robo\Robo::createConfiguration()
from
`$config = new \Robo\Config\Config();`
to
`$config = new \Robo\Config\Config([]);`

Actually function like this is almost pointless `function foo(array $x = null)`, because it can't be called like this `foo(null);` only without argument `foo()` or with a valid argument `foo([]);`

On my project I reverted every dependency back to a working state. I can wait for an official solution.

Thanks anyway

**Comment by greg-1-anderson** [comment]
Actually we never made a stable release of 4.x, so I'll take this as is.

**Comment by greg-1-anderson** [comment]
Whoops. Reverted on the 3.x branch, applied to the 4.x branch.

**Pull request merged**
