### PR TITLE
fixes #951: Updated grasmash/yaml-expander dependency

### LINKED ISSUE #951: Cannot install with Symfony/Yaml 5.0
### Steps to reproduce

Ran `composer require consolidation/robo --dev` in a project that has `symfony/yaml` required at `^5.0.0`.

### Expected behavior

Robo should install

### Actual behavior

Robo fails installation:

```
Problem 1
    - Conclusion: don't install symfony/yaml 4.4.x-dev
    - Conclusion: don't install consolidation/robo 2.1.0
    - Conclusion: remove symfony/translation v5.1.0
    - Installation request for symfony/yaml (locked at v5.1.0, required as ^5.1.0) -> satisfiable by symfony/yaml[v5.1.0].
    - Installation request for consolidation/robo ^2.1 -> satisfiable by consolidation/robo[2.1.0, 2.x-dev].
    - Conclusion: don't install symfony/translation v5.1.0
    - consolidation/robo 2.x-dev requires grasmash/yaml-expander ^1.4 -> satisfiable by grasmash/yaml-expander[1.4.0, 1.x-dev].
    - grasmash/yaml-expander 1.4.0 requires symfony/yaml ^2.8.11|^3|^4 -> satisfiable by symfony/yaml[2.8.x-dev, 3.0.x-dev, 3.1.x-dev, 3.2.x-dev, 3.3.x-dev, 3.4.x-dev, 4.0.x-dev, 4.1.x-dev, 4.2.x-dev, 4.3.x-dev, 4.4.x-dev].
    - grasmash/yaml-expander 1.x-dev requires symfony/yaml ^2.8.11|^3|^4 -> satisfiable by symfony/yaml[2.8.x-dev, 3.0.x-dev, 3.1.x-dev, 3.2.x-dev, 3.3.x-dev, 3.4.x-dev, 4.0.x-dev, 4.1.x-dev, 4.2.x-dev, 4.3.x-dev, 4.4.x-dev].
```

This appears to be because of the `grasmash/yaml-expander` dependency: https://github.com/consolidation/Robo/blob/master/composer.json#L30

The 1.x line of `grasmash/yaml-expander` requires `symfony/yaml` `^2.8.11|^3|^4`: https://github.com/grasmash/yaml-expander/blob/1.4.0/composer.json#L7

The 2.x line still doesn't bump to `symfony/yaml` 5.0 though: https://github.com/grasmash/yaml-expander/blob/2.0.0/composer.json#L9

Have to allow `3.0.0` so that `symfony/yaml` `5.0` will be allowed: https://github.com/grasmash/yaml-expander/blob/3.0.0/composer.json#L8

Related to #917 

### System Configuration

PHP 7.3.18

### PR DESCRIPTION
**Pull request by romanmartushev**
### Overview
This pull request:

- [x] Fixes a bug

### Summary
Updated grasmash/yaml-expander dependency to version that supports symfony/yaml v5

### CODE REVIEW

**Comment by romanmartushev** [comment]
closes #951

**Comment by alsar** [comment]
@romanmartushev why was this closed?

**Comment by romanmartushev** [comment]
The pipeline did not pass and I was not going to up the coverage just for a dependency change.

**Comment by greg-1-anderson** [comment]
I haven't looked at this. In general, I am in favor of major version updates of dependencies if it can be done in a backwards-compatible way. If anyone wants to continue with this investigation, please also use the `|` operator so that existing supported versions continue to work. It is not necessary to support every intermediate version.

**Comment by alsar** [comment]
@greg-1-anderson `grasmash/yaml-expander` v3.0 has a constraint ` "symfony/yaml": "^4 | ^5"`. Robo requires `v4.4.8` as a minumim for Symfony components. So there should not be any backwards incompatibility with bumping the version for `grasmash/yaml-expander`.

**Comment by alsar** [comment]
@greg-1-anderson according to changelogs there are none. At least they shouldn't affect Robo. 
`v2` had internal refactoring and `v3` dropped support for php 5.4 and Symfony 2.

BTW, I don't see that this package is used anywhere in the codebase.

**Comment by greg-1-anderson** [comment]
As I said above, I am in favor of major version upgrades of dependencies if there are no bc breaks because of it. This PR would be acceptable with passing tests. If grasmash/yaml-expander really is not used in this repository, then a PR that removed it as a dependency (and has passing tests) would also be acceptable.

It is plausible that grasmash/yaml-expander is no longer used here. Robo primarily uses consolidation/config for configuration access, which [requires grasmash/expander](https://github.com/consolidation/config/blob/main/composer.json#L24) instead.

**Pull request closed without merging**
