### PR TITLE
Fix #981: PHP 7.3 compatibility issues fixes 1.x

### LINKED ISSUE #981: PHP 7.3 compatibility issues - "Since PHP 7.0, functions inspecting arguments, like func_get_args(), no longer report the original value as passed to a parameter, but will instead provide the current value."
### Steps to reproduce
phpcs -p -s -v --standard=PHPCompatibility vendor/consolidation --runtime-set testVersion 7.3 --report-full=PHP_7_3_Compatibility_vendor_consolidation.log --extensions=php,module,inc -d memory_limit=512M

Generated report from phpcs & found two warnings below -
 
```
FILE: /vendor/consolidation/robo/src/Common/CommandArguments.php
 40 | WARNING | Since PHP 7.0, functions inspecting arguments, like func_get_args(), no longer report the original value as passed to a parameter, but will instead provide the current value. The
    |         | parameter "$args" was used, and possibly changed (by reference), on line 39. (PHPCompatibility.FunctionUse.ArgumentFunctionsReportCurrentValue.NeedsInspection)

FILE: /vendor/consolidation/robo/src/Task/ApiGen/ApiGen.php
 77 | WARNING | Since PHP 7.0, functions inspecting arguments, like func_get_args(), no longer report the original value as passed to a parameter, but will instead provide the current value. The
    |         | parameter "$args" was used, and possibly changed (by reference), on line 76. (PHPCompatibility.FunctionUse.ArgumentFunctionsReportCurrentValue.NeedsInspection)
```

### PR DESCRIPTION
**Pull request by yogeshmpawar**
### Overview
This pull request:

- [ ] Fixes PHP 7.3 Compatibility Issues

### CODE REVIEW

**Comment by greg-1-anderson** [comment]
We'll need to do this for 3.x and 2.x first.

**Comment by yogeshmpawar** [comment]
Sure @greg-1-anderson. I will raise another two PR's for both 3.x & 2.x branch

**Comment by yogeshmpawar** [comment]
@greg-1-anderson - Please review both the PR's -
https://github.com/consolidation/Robo/pull/983
https://github.com/consolidation/Robo/pull/984

**Comment by greg-1-anderson** [comment]
Thanks for fixing this

**Pull request merged**
