### PR TITLE
Add a line space command and a changed the format of the question

### PR DESCRIPTION
**Pull request by andrewtarry**
There was some odd formatting when we tried to start using robo in our project. The question "Should I create a RoboFile" was pushing it's blue background over 2 lines and putting a question mark at the start. I don't know if that was intentional but it does appear a little strange when you first pick up the project. This pull request will change the format so the blue is only on the question and the question mark is only at the end.

In addition there is a new space command that will create an empty line. It was just something we found useful to make it easier to read the output.

### CODE REVIEW

**Comment by burzum** [comment]
>In addition there is a new space command that will create an empty line. It was just something we found useful to make it easier to read the output.

I'm OK with the change but why do you call it `space()`, which is just wrong, instead of `newLine()`? Also I think it could be nice if you could pass an optional argument of how many lines you want to print: `newLine($lines = 1);`

**Comment by DavertMik** [comment]
Could you attach screenshots of how it was and how it become, because I don't see an issue here. 
Yes, the "?" was intentional from start...

**Comment by burzum** [comment]
@andrewtarry any response on this please? :)

**Comment by greg-1-anderson** [comment]
Closed due to lack of activity.

**Pull request closed without merging**
