### PR TITLE
Issue #656: Add \Robo\Collection\TaskForEach::setIterable()

### PR DESCRIPTION
**Pull request by Sweetchuck**
Issue #656 

### Overview
This pull request:

- [ ] Fixes a bug
- [x] Adds a feature
- [ ] Breaks backwards compatibility
- [x] Has tests that cover changes

### CODE REVIEW

**Comment by greg-1-anderson** [comment]
"The provided cwd does not exist" (failure in Appveyor build) is fixed in https://github.com/consolidation/Robo/pull/651.

This should also go away on its own in the next stable release of Symfony/Process.

**Comment by greg-1-anderson** [comment]
Rebase with master and your Appveyor tests should pass.

**Comment by Sweetchuck** [comment]
I think this pull request solves the issue #655 as well. (test included)

**Comment by Sweetchuck** [comment]
What is wrong with this pull request?

**Comment by greg-1-anderson** [comment]
It's perfect; I was waiting for the apveyor tests to be fixed, but somehow didn't notice that you had done that.

**Pull request merged**
