### PR TITLE
Update ConfigProcessor.php

### PR DESCRIPTION
**Pull request by grasmash**
Adding type hints for arrays.

### CODE REVIEW

**Comment by greg-1-anderson** [comment]
I'm ambivalent -- and usually negative towards -- typehints for `array`. While typehints are valuable and generally valuable, typehinting to `array` prevents users from passing an `ArrayObject` here.

**Comment by grasmash** [comment]
Is ArrayObject otherwise usable here? Can an ArrayObject be used with functions like array_map() and array_reduce()?

**Comment by greg-1-anderson** [comment]
I'd need to do a test to confirm. There are some things that ArrayObject can't be used for. If we're already in that space here, then typehinting would be entirely appropriate.

**Comment by grasmash** [comment]
Yes I suspect we are already in that space.

**Comment by greg-1-anderson** [comment]
Confirmed -- ArrayObject doesn't work with any of the php `array_*` methods, so we might as well typehint wherever that is done (most places).

**Pull request merged**
