### PR TITLE
New name for coveralls

### PR DESCRIPTION
**Pull request by szepeviktor**
php-coveralls

### CODE REVIEW

**Comment by szepeviktor** [comment]
Could it be that we do not Coveralls at all?

**Comment by greg-1-anderson** [comment]
This used to work, although whether the failure was introduced by a change in Codeception or a change in the Robo build rules, I am not sure.

**Comment by szepeviktor** [comment]
I think the configuration xml file was removed.

**Comment by szepeviktor** [comment]
No, there was no XML: https://github.com/consolidation/Robo/commit/cb00bedc8942baefbaca9ead7669ce3a3c5e177d

**Comment by greg-1-anderson** [comment]
I think it's okay to omit the configuration xml file; that's working in other projects:

https://travis-ci.org/consolidation/annotated-command/jobs/323953003#L648

**Comment by greg-1-anderson** [comment]
Looks like I broke coveralls when I updated to `satooshi/php-coveralls` and didn't notice that the collapsed build output for the coveralls run contained errors. Renaming the executable is required, seems that a config file might be required now, or some other change.

**Comment by szepeviktor** [comment]
Here it is: https://github.com/php-coveralls/php-coveralls/issues/185
https://github.com/sebastianbergmann/phpunit-documentation/issues/335

**Comment by szepeviktor** [comment]
I leave it up to you!

**Comment by greg-1-anderson** [comment]
Robo is using Codeception, which is built on top of phpunit, but perhaps calls it in such a way that phpunit.xml is not necessarily read or respected.

@DavertMik do you know what to do here?

**Comment by szepeviktor** [comment]
@DavertMik Could you help us?

**Comment by greg-1-anderson** [comment]
Figured it out. Fixed and merged in #723

**Pull request closed without merging**
