### PR TITLE
Parallel syntax check in test:lint

### PR DESCRIPTION
**Pull request by szepeviktor**
### Overview
This pull request:

- [x] Adds a feature

It is very nice: not shell but PHP.

### CODE REVIEW

**Comment by greg-1-anderson** [comment]
Looks pretty good. Did you update the scenario lock files via `composer update`? This should happen automatically via a post-update script.

**Comment by greg-1-anderson** [comment]
What I meant by the comment above is that if you run `composer update` in the Robo project directory, the composer.lock files in the scenario directories will be updated automatically.

**Comment by szepeviktor** [comment]
I've ran `composer update --lock` only. Will it do??

**Comment by greg-1-anderson** [comment]
This is the output I see when I run `composer update --lock`:
```
$ composer update --lock
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 6 installs, 15 updates, 1 removal
  - Removing andrewsville/php-token-reflection (1.4.0)
  - Updating symfony/debug (v3.0.9 => v3.4.2): Loading from cache
  - Updating symfony/console (v2.8.32 => v3.4.2): Loading from cache
  - Installing nikic/php-parser (v3.1.3): Loading from cache
  - Installing goaop/parser-reflection (1.4.0): Loading from cache
  - Updating doctrine/annotations (v1.2.7 => v1.4.0): Loading from cache
  - Updating goaop/framework (1.2.1 => 2.1.2): Loading from cache
  - Updating codeception/aspect-mock (1.0.0 => 2.1.1):  Checking out bf3c000599
  - Updating phpdocumentor/type-resolver (0.3.0 => 0.4.0): Loading from cache
  - Updating phpdocumentor/reflection-docblock (3.2.2 => 3.3.2): Loading from cache
  - Updating symfony/yaml (v3.3.14 => v3.4.2): Loading from cache
  - Updating sebastian/version (1.0.6 => 2.0.1): Loading from cache
  - Installing sebastian/resource-operations (1.0.0): Loading from cache
  - Updating sebastian/recursion-context (1.0.5 => 2.0.0): Loading from cache
  - Installing sebastian/object-enumerator (2.0.1): Loading from cache
  - Updating sebastian/exporter (1.2.2 => 2.0.0): Loading from cache
  - Updating sebastian/environment (1.3.8 => 2.0.0): Loading from cache
  - Updating phpunit/phpunit-mock-objects (2.3.8 => 3.4.4): Loading from cache
  - Installing sebastian/code-unit-reverse-lookup (1.0.1): Loading from cache
  - Updating phpunit/php-code-coverage (2.2.4 => 4.0.8): Loading from cache
  - Installing myclabs/deep-copy (1.7.0): Loading from cache
  - Updating phpunit/phpunit (4.8.36 => 5.7.26): Loading from cache
Generating optimized autoload files
> create-scenario symfony4 'symfony/console:^4.0' --platform-php '7.1.3'

::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
::
:: Create scenario symfony4
::
::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::

+ dir=scenarios/symfony4
+ mkdir -p scenarios/symfony4
+ cp composer.json scenarios/symfony4
+ composer -n --working-dir=scenarios/symfony4 config platform.php 7.1.3
+ composer -n --working-dir=scenarios/symfony4 config minimum-stability stable
+ [[ -z  symfony/console:^4.0 ]]
+ composer -n --working-dir=scenarios/symfony4 require --dev --no-update 'symfony/console:^4.0'
./composer.json has been updated
+ echo vendor
+ true
+ composer -n --working-dir=scenarios/symfony4 config vendor-dir vendor
+ composer -n --working-dir=scenarios/symfony4 update --no-scripts
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Generating optimized autoload files
+ composer -n --working-dir=scenarios/symfony4 config vendor-dir ../../vendor
+ for target in '${AUTOLOAD_DIRECTORIES}'
+ [[ ! -d src ]]
+ ln -s -f ../../src scenarios/symfony4
+ for target in '${AUTOLOAD_DIRECTORIES}'
+ [[ ! -d tests ]]
+ ln -s -f ../../tests scenarios/symfony4
+ cp -f /Users/ganderson/local/consolidation/Robo/vendor/bin/install-scenario scenarios/symfony4/../install
+ chmod +x scenarios/symfony4/../install
> create-scenario symfony2 'symfony/console:^2.8' --platform-php '5.5.9' --no-lockfile

::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
::
:: Create scenario symfony2
::
::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::

+ dir=scenarios/symfony2
+ mkdir -p scenarios/symfony2
+ cp composer.json scenarios/symfony2
+ composer -n --working-dir=scenarios/symfony2 config platform.php 5.5.9
+ composer -n --working-dir=scenarios/symfony2 config minimum-stability stable
+ [[ -z  symfony/console:^2.8 ]]
+ composer -n --working-dir=scenarios/symfony2 require --dev --no-update 'symfony/console:^2.8'
./composer.json has been updated
+ echo vendor
+ false
+ echo composer.lock
+ composer -n --working-dir=scenarios/symfony2 config vendor-dir ../../vendor
+ for target in '${AUTOLOAD_DIRECTORIES}'
+ [[ ! -d src ]]
+ ln -s -f ../../src scenarios/symfony2
+ for target in '${AUTOLOAD_DIRECTORIES}'
+ [[ ! -d tests ]]
+ ln -s -f ../../tests scenarios/symfony2
+ cp -f /Users/ganderson/local/consolidation/Robo/vendor/bin/install-scenario scenarios/symfony2/../install
+ chmod +x scenarios/symfony2/../install
```

Scenario lock files still updated via the post-update scripts.

**Comment by szepeviktor** [comment]
`composer -n --working-dir=scenarios/symfony4 update --no-scripts` has no equivalent in symfony2.

I think all files are included in this PR

**Comment by szepeviktor** [comment]
@greg-1-anderson How to proceed?

**Pull request closed without merging**
