### PR TITLE
Fixes #648: Allow Symfony 4 components in composer.json.

### LINKED ISSUE #648: Symfony 4 support
Some other projects support Symfony 4 already, but Robo pins some Symfony components down to 3.*.

Please implement support for Symfony 4.

### PR DESCRIPTION
**Pull request by greg-1-anderson**
### Overview
This pull request:

- [ ] Fixes a bug
- [X] Adds a feature
- [ ] Breaks backwards compatibility
- [ ] Has tests that cover changes

### Summary
Allow Symfony 4 components in composer.json. Note that Codeception is still pinning us to Symfony 3. This should allow folks using Robo as a Framework to use Symfony 4, albeit without test coverage on Robo with Symfony 4.

After `composer install --no-dev`:
```
$ composer why symfony/console
consolidation/annotated-command  2.8.2       requires  symfony/console (^2.8|^3|^4)  
consolidation/log                1.0.5       requires  symfony/console (^2.8|^3|^4)  
consolidation/output-formatters  3.1.13      requires  symfony/console (^2.8|^3|^4)  
consolidation/robo               dev-master  requires  symfony/console (^2.8|^3|^4)
```

### CODE REVIEW

**Comment by greg-1-anderson** [comment]
This PR, as of c2f6d1e, will now resolve Symfony 4 components if desired. The composer.json is currently pinning to Symfony 3 by way of the extra.platform.php configuration item in the composer.json file. Delete this value (or set it to 7.1.3 or later) and run `composer update`, and you will get Symfony 4 components.

Ad-hoc testing with Symfony 4 shows Robo core to be working. However, the dev versions of Codeception are not working. Running the tests results in:
```
$ ./robo test
 [Testing\Codecept] Executing /Users/ganderson/local/consolidation/Robo/vendor/bin/codecept run 
 [Testing\Codecept] Running /Users/ganderson/local/consolidation/Robo/vendor/bin/codecept run 
 [error]  The provided cwd does not exist. 
```

The tests here are failing because the "lowest" tests require PHP 5.5, but we have set our platform php version to 5.6, which breaks this requirement. I'll improve the highest/lowest testing once our dependencies are ready to merge.

Prerequisites:

- https://github.com/grasmash/yaml-expander/pull/11
- Fix for Codeception problem mentioned above (no issue or PR yet)
- Stable tag for codeception/aspect-mock dev-master

Optional:

https://github.com/php-coveralls/php-coveralls/issues/203#issuecomment-347710771

**Comment by greg-1-anderson** [comment]
It turns out that henrikbjorn/lurker is a fork of https://github.com/flint/Lurker.

**Comment by greg-1-anderson** [comment]
It turns out that the error message above was not caused by Codeception at all, but rather by a new requirement in Symfony/Process 4.x that the cwd be explicitly provided.  This PR causes Robo to subvert this behavior by explicitly providing `getcwd()` to symfony/process if the caller does not provide a working directory. We'll keep this in version 1.x of Robo to provide support for Symfony 4 while maintaining backwards compatibility. Presumably, Robo 2 will be Symfony 4 and later only (ergo PHP 7.1 and later). There's no timeline for starting a Robo 2 branch, though.

At the time of this writing, the test failures are expected, as this branch is set up to use Symfony 4 components, ergo anything earlier than php 7.1 will fail. I expect we'll want the Robo phar to pin to Symfony 3, and allow compatibility with Symfony 4 only for those who use Robo as a framework.

We now have:

- grasmash/yaml-expander now has a stable release
- php-coveralls/php-coveralls now has a stable release, but it's no longer necessary, as guzzle/guzzle is now compatible with Symfony 4.

We still need:

- Stable tag for codeception/aspect-mock dev-master
- codeception/base component updated for Symfony 4

**Comment by DavertMik** [comment]
> At the time of this writing, the test failures are expected, as this branch is set up to use Symfony 4 components, ergo anything earlier than php 7.1 will fail. I expect we'll want the Robo phar to pin to Symfony 3, and allow compatibility with Symfony 4 only for those who use Robo as a framework.

I just faced an issue while executing my Robo script. Due to different symfony/process versions I received this error

```
Uncaught Error: Call to undefined method Symfony\Component\Process\ProcessUtils::escapeArgument()
```
This makes Robo unusable with projects containing Symfony 4 components.
Looks like Symfony 4 should be implemented either as a new version (2.0?) or by adding a compatibility layer.

**Comment by DavertMik** [comment]
Ok, codeception/base 4.0 supports Symfony 4.0 so you can go on :+1:

**Comment by greg-1-anderson** [comment]
I'll give codeception/base a spin and see how it goes.

Note that this PR already solves the `ProcessUtils::escapeArgument` undefined problem.

**Comment by greg-1-anderson** [comment]
@DavertMik `codeception/aspect-mock` is pinning the version of symfony/finder to 3.x:
```
$ composer why symfony/finder
codeception/aspect-mock          2.1.1       requires  symfony/finder (~2.4|~3.0)   
codeception/base                 2.3.7       requires  symfony/finder (>=2.7 <5.0)  
consolidation/annotated-command  2.8.2       requires  symfony/finder (^2.5|^3|^4)  
consolidation/output-formatters  3.1.13      requires  symfony/finder (^2.5|^3|^4)  
consolidation/robo               dev-master  requires  symfony/finder (^2.5|^3|^4)
```
Not a big deal, probably - I'll charge forward ignoring this. Fix it up in a new aspect-mock release when you have a chance.

**Comment by greg-1-anderson** [comment]
Tests are once again passing for php 7.1, so we're just about done here: just need to do highest/lowest testing with Symfony 2, 3 and 4 and make all the tests green.

**Comment by greg-1-anderson** [comment]
Tested all the things! Symfony 2, 3 and 4 all passing.

**Pull request merged**
