### PR TITLE
[WIP] Added task for downloading files with progressbar.

### PR DESCRIPTION
**Pull request by Koc**
Work in progress

### CODE REVIEW

**Comment by greg-1-anderson** [comment]
Please hold this thought for post-#273 work. I'd like to avoid tasks writing to stdout by default. I'd like to see Robo introduce some way that a progress bar could be "attached" to a task when appropriate.

Note also that when #273 goes in, `$this->getOutput()` will disappear -- but you can get it back simply by adding `use IO;` in your task, which is allowed, but deprecated. Hopefully by supporting attachable progress indicators we can also avoid tasks having a reference to getOutput().

**Comment by greg-1-anderson** [comment]
#300 allows tasks access to a progress bar; see ParallelExec and PackPhar for example usage.

You'll have to enhance the interface if you'd like to set the format of the progress bar, though, as at the moment that API is not exposed.

**Comment by Koc** [comment]
@greg-1-anderson will rebase and change code after #300 will be merged

**Comment by greg-1-anderson** [comment]
#300 has been merged.

**Comment by greg-1-anderson** [comment]
Re-open if you want to return to this issue.

**Pull request closed without merging**
