### PR TITLE
Unused property: $defaults

### PR DESCRIPTION
**Pull request by szepeviktor**
### Overview
This pull request:

- [x] Fixes a bug
- [ ] Adds a feature
- [ ] Breaks backwards compatibility
- [ ] Has tests that cover changes
- [ ] Adds or fixes documentation

### Summary
in CollectionBuilder

### CODE REVIEW

**Comment by greg-1-anderson** [comment]
Is this variable still used anywhere?

**Comment by szepeviktor** [comment]
It seems like not: https://github.com/consolidation/Robo/search?q=defaults&unscoped_q=defaults

**Comment by greg-1-anderson** [comment]
Thanks.

**Comment by greg-1-anderson** [comment]
I am going to revert this because I am concerned that a client might still be depending on this property. We can remove it in the next major release.

**Pull request merged**
