### PR TITLE
GitHub stack

### PR DESCRIPTION
**Pull request by greg-1-anderson**
Work in progress -- porting my GitHub API scripts to Robo.

### CODE REVIEW

**Comment by DavertMik** [comment]
That's really great stuff. I was so lazy to implement only release script but it would be cool to automate all github interactions with Robo. Keep the good work!

**Comment by greg-1-anderson** [comment]
I'll re-implement this using https://github.com/KnpLabs/php-github-api as you suggested.

**Comment by greg-1-anderson** [comment]
This isn't ready to merge, so removing "Reviewed" label.

**Comment by greg-1-anderson** [comment]
Will return here later, but with a different implementation as noted above.

**Pull request closed without merging**
